# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
	vb.cpus = 2
  end

  config.vm.define "rkowalskS" do |control|
	control.vm.hostname = "rkowalskS"
	control.vm.network "private_network", ip: "192.168.56.110"
	control.vm.provider "virtualbox" do |vb|
		vb.name = "rkowalskS"
	  end
	control.vm.provision "shell", path: "provision.sh"
    end
end
